name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12 LTS
        uses: actions/setup-node@v1
        with:
          version: 12
      - name: install app dependencies
        run: npm install
      - name: build app
        run: npm run build
